Pre release r1.1 for kyc-match + kyc-fill-in + CHANGELOG + README
camaraproject/KnowYourCustomer pull request #119
Opened 2024-07-26 13:20 UTC by fernandopradocabrillo

#### What type of PR is this?

Add one of the following kinds:
* documentation
* subproject management

#### What this PR does / why we need it:

Generation of first release-candidate for Know Your Customer API family

This first release candidate r1.1 contains the definition and documentation of the release-candidate of the kyc-match APIO v0.2.0-rc.1 and kyc-fill-in v0.1.1-rc.1

2024-07-29 14:06 UTC, hdamker requested changes
Looks good to me, except that the version of kyc-fill-in can't be v0.1.1-rc.1, as there was already a public version with v0.1.1. My recommendation is to use v0.2.0-rc.1 instead as the scope and the base path has been changed in the alignment with Commonalities.

My suggestions assume v0.2.0-rc.1 also for kya-fill-in. If you decide for v0.1.2-rc.1 you need to do the changes yourself.

2024-07-29 14:06 UTC, hdamker commented on documentation/API_documentation/kyc-fill-in-API-Readiness-Checklist.md
> +Checklist for kyc-fill-in 0.1.1-rc in release r1.1
Change according to the selected version number, recommended

```suggestion
Checklist for kyc-fill-in 0.2.0-rc.1 in release r1.1
```

2024-07-29 14:06 UTC, hdamker commented on CHANGELOG.md
> +* kyc-fill-in v0.1.1-rc.1
```suggestion
* kyc-fill-in v0.2.0-rc.1
```

2024-07-29 14:06 UTC, hdamker commented on CHANGELOG.md
> +## kyc-fill-in v0.1.1-rc.1
```suggestion
## kyc-fill-in v0.2.0-rc.1
```

2024-07-29 14:06 UTC, hdamker commented on CHANGELOG.md
> +* n/a
Here the changed scope would be worth to mention: 
```suggestion
* Scope changed from `know-your-customer:fill-in` to `kyc-fill-in:fill-in`
```

2024-07-30 15:41 UTC, fernandopradocabrillo commented
> Looks good to me, except that the version of kyc-fill-in can't be v0.1.1-rc.1, as there was already a public version with v0.1.1. My recommendation is to use v0.2.0-rc.1 instead as the scope and the base path has been changed in the alignment with Commonalities.
> 
> My suggestions assume v0.2.0-rc.1 also for kya-fill-in. If you decide for v0.1.2-rc.1 you need to do the changes yourself.

Hi @ToshiWakayama-KDDI, I'll update the release PR according to @hdamker comments and go for v0.2.0-rc.

2024-08-01 07:56 UTC, sfnuser commented
@fernandopradocabrillo: You may want to update the img references in the yaml specs. Right now they point to Wakayama-san's repo

`<img width="854" alt="KYC_Fill-in_flow" src="https://github.com/ToshiWakayama-KDDI/KnowYourCustomer-Toshi/assets/53090722/f23daa52-bb28-4236-b90d-0184d303f907">`

2024-08-05 11:28 UTC, fernandopradocabrillo commented
> @fernandopradocabrillo: You may want to update the img references in the yaml specs. Right now they point to Wakayama-san's repo
> 
> `<img width="854" alt="KYC_Fill-in_flow" src="https://github.com/ToshiWakayama-KDDI/KnowYourCustomer-Toshi/assets/53090722/f23daa52-bb28-4236-b90d-0184d303f907">`

Thanks @sfnuser! I have raised PR #130 to fix this issue. @ToshiWakayama-KDDI whenever you can please take a look and approve so we can merge.

2024-08-06 16:06 UTC, hdamker approved these changes

2024-08-12 18:36 UTC, hdamker commented
@ToshiWakayama-KDDI @GillesInnov35 The PR needs one code owner approval to allow @fernandopradocabrillo to merge it and create the release.

2024-08-13 07:27 UTC, ToshiWakayama-KDDI approved these changes
Really sorry for the delay.  
Thank you very much, @fernandopradocabrillo , for creating the PR, and @hdamker, for the reminder.

Best,
Toshi

2024-08-13 09:58 UTC, merged

2024-08-13 11:01 UTC, hdamker commented
@ToshiWakayama-KDDI @fernandopradocabrillo Congratulations for the pre-release. The public release for M4 will be much less effort 😄 

I've updated the release tracker pages and closed https://github.com/camaraproject/ReleaseManagement/issues/68.