Add PhoneNumber In FillIn Request Body
camaraproject/KnowYourCustomer pull request #174
Opened 2024-12-13 14:06 UTC by GillesInnov35

Add phoneNumber In Fill-in Request Body

#### What type of PR is this?

* enhancement/feature

#### What this PR does / why we need it:
Add phoneNumber attribute In kyc-fill-in Request Body as optionnal

#### Which issue(s) this PR fixes:

Fixes #https://github.com/camaraproject/KnowYourCustomer/issues/90

2025-01-14 08:04 UTC, ToshiWakayama-KDDI commented
Thank you, @GillesInnov35 .  LGTM. 

Best regards,
Toshi
KDDI

2025-01-14 08:55 UTC, AxelNennker requested changes
Is it customary to have an example both in the parameter description and in the schema definition? https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/number-verification.yaml#L93 does have an example in the schema definition but there is no request example.

2025-01-14 08:57 UTC, AxelNennker requested changes

2025-01-14 08:57 UTC, AxelNennker commented on code/API_definitions/kyc-fill-in.yaml
> +                  phoneNumber: '+34629255833'
The content-type is application/json but the example is not JSON.
```suggestion
                  { "phoneNumber": "+34629255833" }

```

2025-01-14 09:06 UTC, AxelNennker commented
> For this version of the KYC Fill-in API, the request body of the Fill-in Request does not include any parameters/attributes. The above mentioned AuthN/AuthZ/End User consent capturing processes can give the API provider/ MNO the 3rd party identity (with the Access Token) and the end user identity (with the ID Token), so the API provider/ MNO can identify the 3rd party / enterprise customer and the end user. Then, it is up to API provider/ MNO to decide which information the 3rd party will receive by calling the API, and also the API provider / MNO is responsible for security and privacy issues.

This PR MUST change the above text as well because with this PR the Fill-in Request does include a parameter.

There also should be text explaining what the semantic of providing the parameter is if the provided parameter does not match the phoneNumber associated with the acccess token.

2025-01-17 07:24 UTC, GillesInnov35 commented
@AxelNennker , yes you're right, this must be removed.
Thanks
Gilles

2025-01-17 08:30 UTC, GillesInnov35 commented
@AxelNennker , all. I've created PR https://github.com/camaraproject/KnowYourCustomer/pull/182 in order to update fill-in.md and to take into account Axel's comment.

could you have  look on it and if OK could you approve; and also this one. if OK also.
Thanks a lot
Gilles

2025-01-22 14:19 UTC, closed without merging