Updated Age Verification proposal aligned with Spring25
camaraproject/KnowYourCustomer pull request #175
Opened 2024-12-17 11:33 UTC by fernandopradocabrillo

#### What type of PR is this?

Add one of the following kinds:
* enhancement/feature

#### What this PR does / why we need it:
This PR include all the changes and suggestions that haven been made these past months regarding Age Verification in PR #50.
It is a clean version with errors and descriptions aligned with the latest version of Commonalities for Spring25 meta release.

Additionally, it contains a proposal to include two new fields in the response: `contentLock` and `parentalControl`. Both fields come from the feedback of our partners in the UK.

This PR is ment to replace PR #50 as it seems easier to work on a updated fresh copy.

Please leave any comments or changes you feel appropriate.

Thanks!

2024-12-17 15:40 UTC, eric-murray commented on code/API_definitions/age-verification.yaml
> +                code: SERVICE_UNAVAILABLE
There was a typo in CAMARA_common.yaml which should be corrected soon. See [here](https://github.com/camaraproject/Commonalities/pull/359).
```suggestion
                      - UNAVAILABLE
          examples:
            GENERIC_503_UNAVAILABLE:
              description: Service is not available. Temporary situation usually related to maintenance process in the server side
              value:
                status: 503
                code: UNAVAILABLE
```

2024-12-17 15:41 UTC, eric-murray commented on code/API_definitions/age-verification.yaml
> +          description: The birthdate of the customer, in ISO 8601 calendar date format (YYYY-MM-DD).
```suggestion
          description: The birthdate of the customer, in RFC 3339 / ISO 8601 calendar date format (YYYY-MM-DD).
```

2024-12-17 15:47 UTC, eric-murray commented on code/API_definitions/age-verification.yaml
> +                  email: "federicaSanchez.Arjona@gmail.com"
```suggestion
              Two-Legged Access Token Example:
                value:
                  ageThreshold: 18
                  phoneNumber: '+34629255833' # Note: Only required in case a 2-legged flow has been agreed between API Provider and API Consumer; otherwise, do not include phoneNumber
                  idDocument: 66666666q
                  name: Federica Sanchez Arjona
                  givenName: Federica
                  familyName: Sanchez Arjona
                  middleNames: Sanchez
                  familyNameAtBirth: YYYY
                  birthdate: '1978-08-22'
                  email: "federicaSanchez.Arjona@gmail.com"
              Three-Legged Access Token Example:
                value:
                  ageThreshold: 18
                  idDocument: 66666666q
                  name: Federica Sanchez Arjona
                  givenName: Federica
                  familyName: Sanchez Arjona
                  middleNames: Sanchez
                  familyNameAtBirth: YYYY
                  birthdate: '1978-08-22'
                  email: "federicaSanchez.Arjona@gmail.com"
```

2024-12-17 15:48 UTC, fernandopradocabrillo commented on code/API_definitions/age-verification.yaml
> +                code: SERVICE_UNAVAILABLE
oh I wasn't aware, thanks @eric-murray !

2024-12-17 15:57 UTC, eric-murray approved these changes

2024-12-17 16:01 UTC, eric-murray commented
I'm happy with this, so approving. A couple of comments for you to think on:
- Linting is not enabled for this repository, so you might like to run that separately
- You might like to add some guidance around providing the `birthdate` information. If an API consumer really knew the date of birth of the customer, they wouldn't need to use this API! So I assume this information is useful only in that it allows us to verify the customer more quickly in case they API consumer knows the correct date of birth. But if it is incorrect, it will be ignored and other parameters used to verify the identity of the customer.

2024-12-17 16:02 UTC, rartych commented
@fernandopradocabrillo Thanks for this consolidated PR

The latest API Design guidelines add requirements for `api-name` and using it in file name and `servers url `.
I would also take the **location-verification API** as the reference.
Hence I suggest to set `api-name=kyc-age-verification` then we get:

- filename:  `kyc-age-verification.yaml`
- `url: "{apiRoot}/kyc-age-verification/vwip"`
- path: (verb)

 ```
paths:
  /verify:
```

-  security:

```
   - openId:
          - kyc-age-verification:verify
```
 - operationId - _OperationIds are defined in lowerCamelCase_
      `verifyAge` - in line with location verification

- tags - Title Case
         `Age Verification`

2024-12-17 16:12 UTC, fernandopradocabrillo commented
> I'm happy with this, so approving. A couple of comments for you to think on:
> 
> * Linting is not enabled for this repository, so you might like to run that separately
> * You might like to add some guidance around providing the `birthdate` information. If an API consumer really knew the date of birth of the customer, they wouldn't need to use this API! So I assume this information is useful only in that it allows us to verify the customer more quickly in case they API consumer knows the correct date of birth. But if it is incorrect, it will be ignored and other parameters used to verify the identity of the customer.

@eric-murray Thank you for the review! I will pass the linter locally, and I'll raise a PR to include it in the repo later (after Holidays probably haha)

Regarding the birthdate, from TEF we agree... It was in the original proposal and I just left it there, but you are right, it doesn't make much sense.

wdyt about the birthdate @GillesInnov35 @ToshiWakayama-KDDI

2024-12-17 16:28 UTC, fernandopradocabrillo commented
> @fernandopradocabrillo Thanks for this consolidated PR
> 
> The latest API Design guidelines add requirements for `api-name` and using it in file name and `servers url `. I would also take the **location-verification API** as the reference. Hence I suggest to set `api-name=kyc-age-verification` then we get:
> 
> * filename:  `kyc-age-verification.yaml`
> * `url: "{apiRoot}/kyc-age-verification/vwip"`
> * path: (verb)
> 
> ```
> paths:
>  /verify:
> ```
> 
> * security:
> 
> ```
>    - openId:
>           - kyc-age-verification:verify
> ```
> 
> * operationId - _OperationIds are defined in lowerCamelCase_
>   `verifyAge` - in line with location verification
> * tags - Title Case
>   `Age Verification`

Thanks @rartych, I have applied the changes to align with commonalities guidelines

2024-12-17 16:34 UTC, HuubAppelboom commented
> I'm happy with this, so approving. A couple of comments for you to think on:
> 
> * Linting is not enabled for this repository, so you might like to run that separately
> * You might like to add some guidance around providing the `birthdate` information. If an API consumer really knew the date of birth of the customer, they wouldn't need to use this API! So I assume this information is useful only in that it allows us to verify the customer more quickly in case they API consumer knows the correct date of birth. But if it is incorrect, it will be ignored and other parameters used to verify the identity of the customer.

@eric-murray Hi Eric, this  birthdate information is what the use claims it to be. If it it does not match, you are sure the end user is not the contract owner, and you can not return a reasonable answer.  We propose to reply with "not_available" and not provide an identityMatchScore. See also the proposal I made here: https://github.com/camaraproject/KnowYourCustomer/issues/81#issuecomment-2425951384

2024-12-17 16:47 UTC, eric-murray commented
@HuubAppelboom
> If it it does not match, you are sure the end user is not the contract owner, and you can not return a reasonable answer. 

OK. So the API also allows the API consumer to confirm whether the DoB they have been given by the customer is correct.

2024-12-17 17:31 UTC, HuubAppelboom commented
@eric-murray Yes, the DoB is then used as a first tollgate check. If it matches, you continue to processing the other input parameters that have been provided with which you can calculate the aggregate identity match score.

2024-12-18 04:49 UTC, ToshiWakayama-KDDI commented
> > @fernandopradocabrillo Thanks for this consolidated PR
> > The latest API Design guidelines add requirements for `api-name` and using it in file name and `servers url `. I would also take the **location-verification API** as the reference. Hence I suggest to set `api-name=kyc-age-verification` then we get:
> > 
> > * filename:  `kyc-age-verification.yaml`
> > * `url: "{apiRoot}/kyc-age-verification/vwip"`
> > * path: (verb)
> > 
> > ```
> > paths:
> >  /verify:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * security:
> > 
> > ```
> >    - openId:
> >           - kyc-age-verification:verify
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * operationId - _OperationIds are defined in lowerCamelCase_
> >   `verifyAge` - in line with location verification
> > * tags - Title Case
> >   `Age Verification`
> 
> Thanks @rartych, I have applied the changes to align with commonalities guidelines

Hi @Fernando, @Rafal, all,

Thank you for intensive review of Age Verification API.

But, from KDDI side, I cannot accept all of this kind of last minute fundamental changes.  We have already started implementation work, as this API has been discussed since January and the discussion had become stable before. 

From KDDI side, I would like to ask to revert url and path to the previous ones, i.e. 

- url: {apiRoot}/kyc-ageverify/vwip
- path: /ageverify
- Consecurtly I would propose to change the filename to: kyc-ageverify.yaml.

I do not think the above is not against commonalities guidelines.

Sorry for the late response due to the time difference, but your understanding would be appreciated.

Best reagrds,
Toshi
KDDI

2024-12-18 04:55 UTC, ToshiWakayama-KDDI commented
Hi all,

I am checking other changes e.g. error responses, made by European colleagues during my night.  Please allow me to take some time and comments. 

Best regards,
Toshi
KDDI

2024-12-18 08:57 UTC, fernandopradocabrillo commented
> Hi @fernando, @rafal, all,
> 
> Thank you for intensive review of Age Verification API.
> 
> But, from KDDI side, I cannot accept all of this kind of last minute fundamental changes. We have already started implementation work, as this API has been discussed since January and the discussion had become stable before.
> 
> From KDDI side, I would like to ask to revert url and path to the previous ones, i.e.
> 
> * url: {apiRoot}/kyc-ageverify/vwip
> * path: /ageverify
> * Consecurtly I would propose to change the filename to: kyc-ageverify.yaml.
> 
> I do not think the above is not against commonalities guidelines.
> 
> Sorry for the late response due to the time difference, but your understanding would be appreciated.
> 
> Best reagrds, Toshi KDDI

Hi @ToshiWakayama-KDDI,

Sorry, I think you mentioned this before. For me there is no problem in reverting to the previous name and aligning the filename.

I like this one better, by I can live with it 😄

2024-12-19 07:52 UTC, claraserranosolsona commented
Hi @GillesInnov35 , @ToshiWakayama-KDDI , are you happy with the PR? 
Let us know if you have any additional comment, as I understood the objective would be to close the RC within this week 
Many thanks in advance
Clara

2024-12-19 09:44 UTC, eric-murray commented
@ToshiWakayama-KDDI 
> But, from KDDI side, I cannot accept all of this kind of last minute fundamental changes. We have already started implementation work, as this API has been discussed since January and the discussion had become stable before.

The registered name for this API in the [API Backlog WG](https://github.com/camaraproject/APIBacklog/blob/main/documentation/APIbacklog.md) is, and always has been, "KYC Age Verification". If you want it to be known as "KYC Age Verify", then you should submit a PR to that WG to get it changed. Even then, the name in the URL should be `/kyc-age-verify` (i.e. `url: {apiRoot}/kyc-age-verify/vwip`) following Commonalities rules.

2024-12-19 09:47 UTC, eric-murray commented on code/API_definitions/kyc-age-verification.yaml
> +  - url: "{apiRoot}/kyc-ageverify/vwip"
```suggestion
  - url: "{apiRoot}/kyc-age-verify/vwip"
```

2024-12-19 09:53 UTC, GillesInnov35 commented
hi @claraserranosolsona, I've discussed internally with my team. Regarding parentControl and contentBlock, they submitted those ideas
- each country should have possibility to decide/manage if those kind of information should be returned 
- the requester should indicate clearly if information are expected (scope or claims).
I've scheduled a point this afternoon. I guess I'll have a decision from our side 
Thanks a lot
BR
Gilles

2024-12-19 09:56 UTC, rartych commented on code/API_definitions/kyc-age-verification.yaml
> +          - kyc-ageverify:ageverify
If we keep the `\verify` in paths then the scope should be:
```suggestion
          - kyc-age-verify:verify
```

2024-12-19 10:06 UTC, rartych commented on code/API_definitions/kyc-age-verification.yaml
> +  - url: "{apiRoot}/kyc-ageverify/vwip"
The full request would look like `"{apiRoot}/kyc-age-verify/vwip/verify"`, but we can decide and change the names in separate PR as it is not related to API functionality.

The guidelines were update with: https://github.com/camaraproject/Commonalities/pull/333

2024-12-19 14:24 UTC, ToshiWakayama-KDDI commented on code/API_definitions/kyc-age-verification.yaml
> +  - url: "{apiRoot}/kyc-ageverify/vwip"
Hi @eric-murray , @rartych ,

Thanks.  Then  I will submit a PR to API Backlog WG.  If the API name is KYC Ageverify, it would be url "{apiRoot}/kyc-ageverify/vwip".  Am I correct?

Thanks,
Toshi

2024-12-19 14:28 UTC, eric-murray commented on code/API_definitions/kyc-age-verification.yaml
> +  - url: "{apiRoot}/kyc-ageverify/vwip"
> Thanks. Then I will submit a PR to API Backlog WG. If the API name is KYC Ageverify, it would be url "{apiRoot}/kyc-ageverify/vwip". Am I correct?

Yes, though expect some debate on calling an API "KYC Ageverify".

2024-12-19 14:31 UTC, ToshiWakayama-KDDI commented on code/API_definitions/kyc-age-verification.yaml
> +          - kyc-ageverify:ageverify
Hi @rartych ,

Thanks.  I have asked to keep the original path 'ageverify', instead of 'verify'.  If url becomes either of kyc-ageverify or kyc-age-verify, 'ageverify' can be used, I understand.  Correct?

Thanks,
Toshi

2024-12-19 16:08 UTC, GillesInnov35 commented
@claraserranosolsona, after an discussion at Orange see bellow our quick comments 
- those information are not determinist while the other are determinist (ageCheck, verifiedStatus). 
- if we decide to include those information, they should be returned only if the developer ask for them (request body or claims) 
- some countries will probalbly decide not to return those information. In that case, will the returned value be unavailable ? 
Thanks 
BR
Gilles

2024-12-19 16:41 UTC, rartych commented on code/API_definitions/kyc-age-verification.yaml
> +          - kyc-ageverify:ageverify
There is no clear guideline but in section 3.1 there is such a sentence:

> When the POST method is used, the resource in the path must be a verb (e.g. retrieve-location and not location) to differentiate from an actual resource creation.

One can say that the verb is `verify`, so the kebab case should be used: `verify-age` or `age-verify` (but it starts with not a verb)

`"{apiRoot}/kyc-ageverify/vwip/ageverify"` looks redundant to me, but we can leave it for final review

2024-12-20 06:37 UTC, ToshiWakayama-KDDI commented
> Hi @GillesInnov35 , @ToshiWakayama-KDDI , are you happy with the PR? Let us know if you have any additional comment, as I understood the objective would be to close the RC within this week Many thanks in advance Clara

Hi @claraserranosolsona , 

I should comment it is not possible for us to complete checking of these big bunches of changes from the previous version.  I am still discussing with my implementation / product teams.  Fortunately, I do not think we have to close the RC within this week now, and I think we should extend the target date of the RC.

Regarding the addtional paramters, 'contentLock' and 'parentalControl', as our quick response, we should be fine with them as long as they are optional and they don't add mandatory logic to the API backend.  (In addition, I am not sure if they are related to verifying age, but it is fine with me.)

Many thanks,
Toshi

2024-12-23 05:24 UTC, ToshiWakayama-KDDI commented on code/API_definitions/kyc-age-verification.yaml
> +          - kyc-ageverify:ageverify
Hi @rartych , @eric-murray , @fernandopradocabrillo ,

I had one question during my internal discussion regarding this part.

> Security:
>   -openId:
>       -kyc-ageverify:ageverify

(Currently the scope is kyc-ageverify:ageverify.)

Can we keep the first part 'kyc-ageverify', even though we change the filename to kyc-age-verification.yaml and change the url to {apiRoot}/kyc-age-verification/vwip ?  In another wey, should the first part 'kyc-ageverify' be aligned with 'api-name', i.e. kyc-age-verification?

Many thanks,
Toshi

2025-01-03 13:06 UTC, ToshiWakayama-KDDI commented
Hi @fernandopradocabrillo , @GillesInnov35 , @eric-murray , @rartych , all

I have been working internally on the recently proposed changes to get the Age Verificaiton yaml aligned with the latest Commonalities.  We are investigating some work around, in order for us to accept the proposed changes.  Now we are on new-year holiday in Japan, so, it is to be confirmed early next week, i.e. on 6th January at the earliest.  Please give me some more time.

Let me double-check the proposed changes as below:
 
- API-name: KYC Age Verification (decided by API Backlog and GSMA Product WS from the beginning)


-> Based on the API name, 

- filename: kyc-age-verification.yaml

- url: "{apiRoot}/kyc-age-verification/vwip"

->As 'paths' should be verb, 

- paths:  
       /verify:

->based on the above, 

- security: 
     -openId:  
    -kyc-age-verification:verify


Please let me know if my understanding above is not correct.

Many thanks,
Toshi

2025-01-07 05:11 UTC, ToshiWakayama-KDDI commented
Hi @fernandopradocabrillo , @GillesInnov35 , @eric-murray , @rartych , all

I am glad to inform you that we/KDDI can accept the proposed changes as written down in my previous comment, above, for Age Verification initial version / Spring25 Meta version.

So, no API name change will be challenged in API Backlog.

I would like to ask Fernando to modify the yaml file accordingly.

Thanks.

2025-01-07 05:13 UTC, ToshiWakayama-KDDI commented on code/API_definitions/kyc-age-verification.yaml
> +  - url: "{apiRoot}/kyc-ageverify/vwip"
As commented in the main conversation, url "{apiRoot}/kyc-age-verification/vwip" is now fine with us/KDDI.

Thanks
Toshi

2025-01-07 05:15 UTC, ToshiWakayama-KDDI commented on code/API_definitions/kyc-age-verification.yaml
> +          - kyc-ageverify:ageverify
As commented in the main conversation, "kyc-age-verification:verify" is now fine with us/KDDI.

Thanks,
Toshi

2025-01-07 19:18 UTC, AxelNennker commented
Note: Please remember the OIDF presentation from March 2024 which included Age Verification
https://github.com/camaraproject/KnowYourCustomer/blob/f6c75cf4ed2db6d08287d23dfe468a034f8ebfdd/documentation/MeetingMinutes/MOM-2024-03-19.md#oidf-presentation-re-age-verification

This OIDF specification defines that Advanced Syntax: https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#name-example-age-verification

Interesting side-note: Requests should be signed

> Integrity protection and authentication of authentication requests can be achieved in particular by
using Pushed Authorization Requests [[RFC9126](https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#RFC9126)] to send requests server-to-server with authentication of the RP, or
using JWT-Secured Authorization Requests [[RFC9101](https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#RFC9101)] to sign the authentication request parameters.

2025-01-07 20:17 UTC, AxelNennker requested changes
Are the additional functions essential for the commercial success? Otherwise they lead to more trouble than they are worth. Keep it simple.

2025-01-07 20:17 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    - If the network subscription cannot be identified from the provided parameters (e.g. the subscription identifier is not associated with any customer of the CSP), a `404 IDENTIFIER_NOT_FOUND` err
What is an "authentication token"? API access token? Isn't that error then 401 Unauthorized? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

IDENTIFIER_NOT_FOUND can be used to implement a Telco Finder. If the API consumer has a valid 3-legged access token then the this error cannot happen, right? Is this error for 2-legged tokens only?

2025-01-07 20:17 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    - If the API consumer has a valid access token but is not authorised to request an age verification for the specified network subscription, then a `403 PERMISSION_DENIED` error is returned.
How can that be? The API consumer should never get a valid access token in this case, right?
At onboarding time of the API consumer includes the scope "kyc-age-verification:verify" or not. And then the access token is created or not.

2025-01-07 20:17 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +        As it is possible that the person holding the contract and the person using the line may not be the same, the endpoint also admits a list of optional properties to be included in the request
How does including additional data improve the "identification"? What is the threat model?

2025-01-07 20:17 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +                value:
The content has the content-type application/json but the example value is no JSON.

2025-01-07 20:17 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +                  email: "federicaSanchez.Arjona@gmail.com"
```suggestion
                  email: "federicaSanchez.Arjona@example.com"
```

2025-01-07 20:17 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +                  email: "federicaSanchez.Arjona@gmail.com"
```suggestion
                  email: "federicaSanchez.Arjona@example.com"
```

2025-01-07 20:32 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +    This API provides the customer with the ability to check if the user of the line is older than a provided age, in order to provide API customer's age-restricted services, access to its age-restri
I think the goal to verify the age of the end user in most use cases, not that of the subscriber (although the subscriber data is used for the verification)

2025-01-07 20:46 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +      Additionally, as optional function, provides (1) if age check is done against another form of official identification or not (verifiedStatus), (2) an overall score of how certain is the respons
Official Identification can be defined as Identity Document which is legally accepted as a means to verify someone's identity. We don't want to define which trust framework is used for this, but more whether data has been verified or not at all.

2025-01-07 20:52 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +    - `verifiedStatus`: true if the information provided was checked against another form of official identification, otherwise false.
note that government issued is not always correct, for example for driver licenses this can be different, like that it is issued by semi-government organisations. Suggest to change it to legally accepted identifcation document. What is legally accepted can also vary per country.

2025-01-07 20:55 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +    - `identityMatchScore`: The overall score of identity information available in the Operator, information either provided in the request body comparing it to the one that the MNO holds or directly
The MNO can publish the algorithm used, if need be.  Note that algorithm may vary depending on the quality of the data the MNO holds, so it is difficult to come with a algorithm which will work in all cases.

2025-01-07 20:58 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +        As it is possible that the person holding the contract and the person using the line may not be the same, the endpoint also admits a list of optional properties to be included in the request
What needs to be verified is whether the end user is the same person as the subscriber (user) to a certain level of degree of certainty. That is what calculating the identity match score is for

2025-01-07 21:09 UTC, HuubAppelboom commented
> Note: Please remember the OIDF presentation from March 2024 which included Age Verification https://github.com/camaraproject/KnowYourCustomer/blob/f6c75cf4ed2db6d08287d23dfe468a034f8ebfdd/documentation/MeetingMinutes/MOM-2024-03-19.md#oidf-presentation-re-age-verification
> 
> This OIDF specification defines that Advanced Syntax: https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#name-example-age-verification
> 
> Interesting side-note: Requests should be signed
> 
> > Integrity protection and authentication of authentication requests can be achieved in particular by
> > using Pushed Authorization Requests [[RFC9126](https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#RFC9126)] to send requests server-to-server with authentication of the RP, or
> > using JWT-Secured Authorization Requests [[RFC9101](https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#RFC9101)] to sign the authentication request parameters.

@AxelNennker If you look at the Advanced Syntax specification, I think this specification is much to broad on the one hand for age verification (you can define a lot more complex use cases) which also ha  a strong risk in it that it will be used for cases which are not intended. I think we are much better of with a well defined API, including wel defined options, than giving relying parties a toolbox by which can do a lot of things.  Furthermore, if you look into the specs, I doubt you can for example also  calculate a Jaro-Winkler score with it

2025-01-07 22:18 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +    - If the API consumer has a valid access token but is not authorised to request an age verification for the specified network subscription, then a `403 PERMISSION_DENIED` error is returned.
This is probably for the 2 legged flow, not?

2025-01-08 07:20 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    This API provides the customer with the ability to check if the user of the line is older than a provided age, in order to provide API customer's age-restricted services, access to its age-restri
@HuubAppelboom I am struggling with the word "line". I amended my suggestion and reintroduced "user" but removed "of the line".

2025-01-08 08:14 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +    This API provides the customer with the ability to check if the user of the line is older than a provided age, in order to provide API customer's age-restricted services, access to its age-restri
@AxelNennker It would be more precise to use the word End-User, as it is defined in the Glossary of Identity and Consent Management

2025-01-08 09:59 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    - `verifiedStatus`: true if the information provided was checked against another form of official identification, otherwise false.
I updated my suggestion

2025-01-08 13:10 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    - If the API consumer has a valid access token but is not authorised to request an age verification for the specified network subscription, then a `403 PERMISSION_DENIED` error is returned.
To clarify: my comment is about this item on the list
> - If the API consumer has a valid access token but is not authorised to request an age verification for the specified network subscription, then a `403 PERMISSION_DENIED` error is returned.

With 2-legged flow there is a scope in the client credentials token request, right?
https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2

The 2-legged token request with OAuth2 client_credentials might look like in this example, right?:
```
POST /token HTTP/1.1
Host: server.example.com
Authorization: Bearer eyJhbGciOiJFUzI1NiJ9.ewogICJqdGkiOiJteUpXVElkMDAxIiwKICAic3ViIjoiMzgxNzQ2MjM3NjIiLAogICJpc3MiOiIzODE3NDYyMzc2MiIsCiAgImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC9hcGkvYXV0aC90b2tlbi9kaXJlY3QvMjQ1MjMxMzgyMDUiLAogICJleHAiOjE1MzYxNjU1NDAsCiAgImlhdCI6MTUzNjEzMjcwOAp9Cg.YB4gdhWUGRjWEsEbKDs7-G2WFH2oYz7bAEP5AtegHXInkY9ncA2V3IoA6O_HVQuFxyCRIklrxsMk32MfNF_ABA
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope="dpv:FraudPreventionAndDetection kyc-age-verification:verify"
```

The resulting access token is then valid for the scope `kyc-age-verification:verify`. So, `403 PERMISSION_DENIED` cannot happen, I think.

2025-01-08 13:58 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +        As it is possible that the person holding the contract and the person using the line may not be the same, the endpoint also admits a list of optional properties to be included in the request
What about this scenario: A minor is using their parent's mobile phone to access age-restricted content on the API consumer's website.

The minor enters all the parents attributes into the API consumer webpage. 
Variant 1) CIBA
The API consumer sends a signed CIBA request to the API provider. The API Provider sends a message to the subscriber's mobile phone that is in the hands of the minor. The minor enters e.g. a received OTP code into the API consumers webpage and the API consumer retrieves the access token.
Then the API consumer requests age-verification with those parameter:

```
POST /ageverify
Host: camaraapi.example.com
Authorization: Bearer SplxlOBeZQQYbYS6WxSbIA
Content-Type: application/json

{
  "ageThreshold": 18,
  "idDocument": "66666666q",
  "name": "Federica Sanchez Arjona",
  "givenName": "Federica",
  "familyName": "Sanchez Arjona",
  "middleNames": "Sanchez",
  "familyNameAtBirth": "YYYY",
  "birthdate": "1978-08-22",
  "email": "federicaSanchez.Arjona@gmail.com"
}
```

Sending the attributes in the age-verification process does help in verifying whether the end user (minor) is the same person as the subscriber (user)(parent).

Variant 2) OIDC authorization code flow
The API consumer sends a signed OIDC code request with `max_age=0`.
Note `max_age` is [mandatory to implement for all OIDC server](https://openid.net/specs/openid-connect-core-1_0.html#ServerMTI).
The minor does not know the subscriber credentials and the flow stops. Access to the age-protected contents is prevented.

Security considerations: 
- all requests for code and tokens for age-verification MUST be signed by the API consumer. The API provider MUST validate the signatur. 
- all access tokens SHOULD be sender-constrained e.g. by using DPoP.

2025-01-08 14:17 UTC, AxelNennker commented
> > Note: Please remember the OIDF presentation from March 2024 which included Age Verification https://github.com/camaraproject/KnowYourCustomer/blob/f6c75cf4ed2db6d08287d23dfe468a034f8ebfdd/documentation/MeetingMinutes/MOM-2024-03-19.md#oidf-presentation-re-age-verification
> > This OIDF specification defines that Advanced Syntax: https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#name-example-age-verification
> > Interesting side-note: Requests should be signed
> > > Integrity protection and authentication of authentication requests can be achieved in particular by
> > > using Pushed Authorization Requests [[RFC9126](https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#RFC9126)] to send requests server-to-server with authentication of the RP, or
> > > using JWT-Secured Authorization Requests [[RFC9101](https://openid.bitbucket.io/ekyc/openid-connect-advanced-syntax-for-claims.html#RFC9101)] to sign the authentication request parameters.
> 
> @AxelNennker If you look at the Advanced Syntax specification, I think this specification is much to broad on the one hand for age verification (you can define a lot more complex use cases) which also has a strong risk in it that it will be used for cases which are not intended. I think we are much better of with a well defined API, including wel defined options, than giving relying parties a toolbox by which can do a lot of things. Furthermore, if you look into the specs, I doubt you can for example also calculate a Jaro-Winkler score with it, so on the other hand the toolbox is also too limited.

@HuubAppelboom I agree, I just wanted to remind the WG that OIDF is discussing age-verfication for ages. Age verification was already discussed in OpenId 1.0 and early [IIW](https://internetidentityworkshop.com/)s. Currently most work is done in the field of Verifiable Credentials/Presentations, I think.

2025-01-08 14:22 UTC, AxelNennker commented
There are examples of law that requires that e.g. in a web forum participants MUST be children, that is UNDER a certain age. 

E.g.: [COPPA](https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa) and [CIPA](https://www.fcc.gov/consumers/guides/childrens-internet-protection-act)

Maybe change ageThreshHold to ageLowerBound and introduce ageUpperBound, or something?

2025-01-08 14:25 UTC, AxelNennker commented
Should the API provider prevent the API consumer from testing all values from 0 to 100 to find the birth-year of a user?

The API consumer can send many requests for one user and if we are not careful the API provider can find the exact birth-year.

2025-01-08 14:32 UTC, AxelNennker commented
Is `max_age=0` mandatory for age-verification?
I think, that IF we want the age of the End-User to be verified then the End-User MUST authenticate.
Otherwise, all we verify is the age of the subscriber, I think.

2025-01-08 14:36 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +        As it is possible that the person holding the contract and the person using the line may not be the same, the endpoint also admits a list of optional properties to be included in the request
@AxelNennker  Regarding variant 1. If the end user (a minor) is entering all the details of the susbcriber (a parent) with the API Consumer, the Age Verification will of course not work.  We assume here that the minor is entering his/her own data, and email address etc. In case the minor is clever and knows about this and enters all the data, the API Consumer can always send a confirmation mail that he is granted access to the service, see what happens....

If you are looking for a age verifcation which is done at a higher level of assurance, you are probably better of with a different product, like for instance an eIDAS wallet.

2025-01-08 14:45 UTC, AxelNennker commented
What would be the `purpose` usually associated with this API?
https://w3c.github.io/dpv/2.0/dpv/modules/purposes.html#AgeVerification seems very generic.

If the API consumer is a bank and the legal age for a minor having a bank account is 14, what `purpose` would the API consumer then send? This is not a problem of this subproject, but somewhere this has to be defined, I think.

2025-01-08 15:30 UTC, HuubAppelboom commented
> There are examples of law that requires that e.g. in a web forum participants MUST be children, that is UNDER a certain age.
> 
> E.g.: [COPPA](https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa) and [CIPA](https://www.fcc.gov/consumers/guides/childrens-internet-protection-act)
> 
> Maybe change ageThreshHold to ageLowerBound and introduce ageUpperBound, or something?

I would leave it for now as is. I have not seen any internet service yet where adults are excluded.  Usually it is something like an internet filter which excludes content for adults, and you can only be excluded from the filter if you prove you are an adult.

2025-01-08 15:32 UTC, HuubAppelboom commented
> What would be the `purpose` usually associated with this API? https://w3c.github.io/dpv/2.0/dpv/modules/purposes.html#AgeVerification seems very generic.
> 
> If the API consumer is a bank and the legal age for a minor having a bank account is 14, what `purpose` would the API consumer then send? This is not a problem of this subproject, but somewhere this has to be defined, I think.

@AxelNennker I think you can still ctegorize this under fraud prevention (the use is actually not allowed access to a service, and is committing fraude to ge the access by claiming he is older than 18)

2025-01-08 15:39 UTC, HuubAppelboom commented
> Is `max_age=0` mandatory for age-verification? I think, that IF we want the age of the End-User to be verified then the End-User MUST authenticate. Otherwise, all we verify is the age of the subscriber, I think.

@AxelNennker We see a lot of use cases where the API consumer wants to have a bit more assurance than asking whether you are older than 18.  And in many cases, the authentication is not necessary. For example for a subscrption on a monthly lottery ticket you need to be older than 18.  What happens in that minors do register the tickets on their own name (otherwise you run the risk of not getting paid in case of a big prize), but lie about their age.  Authentication is in this case not necessary, just confirming that the name is associated with a phone number and a date of birth which is 18+ is sufficient.  The API consumer is always looking for as low as possible friction, and it is best to leave the decision on what authentication is need to the API Consumer.

2025-01-08 15:50 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +    - If the API consumer has a valid access token but is not authorised to request an age verification for the specified network subscription, then a `403 PERMISSION_DENIED` error is returned.
In case the end user is excluded/blocked from API services this may come about with a 2 legged flow.  You may want to offer this kind of blocking as a service for example for VIPs or other special interest groups, where privacy concerns may prevalate.

2025-01-08 15:53 UTC, HuubAppelboom commented
> Should the API provider prevent the API consumer from testing all values from 0 to 100 to find the birth-year of a user?
> 
> The API consumer can send many requests for one user and if we are not careful the API provider can find the exact birth-year.

@AxelNennker The same applies to other attributes, like for example housenumber, or first name.  Best is probably to monitor for this kind of behaviour, and lock accounts that show abuse or search behaviour.

2025-01-09 09:47 UTC, fernandopradocabrillo commented
Hi, @GillesInnov35, @ToshiWakayama-KDDI, @HuubAppelboom 
As discussed in the last meeting with @claraserranosolsona, I have updated the proposal including the properties `contentLock`and `parentLock` as optional input flags in the request body to indicate if the corresponding response properties should be returned.
Thanks!

2025-01-09 09:51 UTC, GillesInnov35 reviewed
hi @fernandopradocabrillo , concerning contentLock an parentControl, name of flag in the request should not be the same as it is 2 different parameters (a boolean and a string). WDYT
Gilles

2025-01-09 09:59 UTC, HuubAppelboom commented
> Is `max_age=0` mandatory for age-verification? I think, that IF we want the age of the End-User to be verified then the End-User MUST authenticate. Otherwise, all we verify is the age of the subscriber, I think.

For many cases, legitimate interests can be used, and in this case you don't need to authenticate at all, as long as you keep it a verification product, and the level of assurance that can ben obtained (including the optional identityMatchScore is sufficient for the API consumer.

In case a higher level of assurance regarding age is required or legitimate interest can not be used (depending on the use case), you may need another product, which is more similar to a eIDAS wallet (or at least something of a similar level of assurance).
In that case, and alternative approach to max_age=0 could be to solve it in the consent acquistion process of CAMARA, and make sure that next to acquiring the explict end user consent (with a tick box) you also let the subcriber provide the credentials required.  This is however a different product in my opnion, similar to teh difference between KYC Match and KYC Fill-in.

2025-01-09 10:48 UTC, fernandopradocabrillo commented
> hi @fernandopradocabrillo , concerning contentLock an parentControl, name of flag in the request should not be the same as it is 2 different parameters (a boolean and a string). WDYT Gilles

I also thought about it yerterday while doing it, but I ended up going with the same names. We can go for something like: `includeParentalControl` and `includeContentLock`. Or in the response change to `parentalControlOn` or `parentalControlActive`.

I don't have any preference

2025-01-09 14:52 UTC, GillesInnov35 commented
hi @fernandopradocabrillo , thanks a lot for your proposal (includeParentalControl and includeContentLock), it suits me well. The objective is to allow consumer to request those 2 added parameters or not.

All, WDYT ?

Gilles

2025-01-09 16:16 UTC, fernandopradocabrillo commented on code/API_definitions/kyc-age-verification.yaml
> +    - `verifiedStatus`: true if the information provided was checked against another form of official identification, otherwise false.
I think we can include this, can we rephrase it a bit? I find it a little bit confusing, but I get the idea

```suggestion
    - `verifiedStatus`: Indicate `true` if the information provided has been compared against information based on an identification document legally accepted as an age verification document, otherwise indicate `false`.
```

2025-01-09 16:18 UTC, fernandopradocabrillo commented
> Hi @fernandopradocabrillo , @GillesInnov35 , @eric-murray , @rartych , all
> 
> I am glad to inform you that we/KDDI can accept the proposed changes as written down in my previous comment, above, for Age Verification initial version / Spring25 Meta version.
> 
> So, no API name change will be challenged in API Backlog.
> 
> I would like to ask Fernando to modify the yaml file accordingly.
> 
> Thanks.

Hi @ToshiWakayama-KDDI, It has been modified accordingly! Thank you very much

2025-01-09 16:20 UTC, fernandopradocabrillo commented on code/API_definitions/kyc-age-verification.yaml
> +    - If the network subscription cannot be identified from the provided parameters (e.g. the subscription identifier is not associated with any customer of the CSP), a `404 IDENTIFIER_NOT_FOUND` err
Yes, it is the access token, I'll update the text to reflect this more clear.

Regarding the IDENTIFIER_NOT_FOUND not found error, it is the error accepted in latest Commonalities release. It's common for all APIs that go to meta Spring25.

2025-01-10 12:35 UTC, fernandopradocabrillo commented
Thanks @ToshiWakayama-KDDI, @GillesInnov35  I have updated the name proposal and the descriptions to reflect the use of this functionality, please take a look and let me know if it suits you.

2025-01-10 22:06 UTC, AxelNennker requested changes

2025-01-10 22:06 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    This API provides the customer with the ability to check if the user of the line is older than a provided age, in order to provide API customer's age-restricted services, access to its age-restri
I changed the suggestion to "End-User"

2025-01-11 12:25 UTC, AxelNennker requested changes

2025-01-11 12:25 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +      Additionally, as optional function, provides (1) if age check is done against another form of official identification or not (verifiedStatus), (2) an overall score of how certain is the respons
I think attributes of a person that are not well defined, will get us into trouble and will lead to interoperability problems. What are parental control exactly? If the end-user is of legal age, e.g. age_over_18 and age_over_21, BUT still there are parental controls in place, then could that mean the end-user is mentally-challenged and some if their rights were lawfully revoked? "parental control" would then be health data, which has special protection in most jurisdictions. Similar with contenLock? 
 I think these additional attribute, parental control or content block or ..., need to be specified. 
 I would add them to fill-in and match, because I these attributes should not be mixed with age-verification.

2025-01-13 11:24 UTC, claraserranosolsona commented on code/API_definitions/kyc-age-verification.yaml
> +      Additionally, as optional function, provides (1) if age check is done against another form of official identification or not (verifiedStatus), (2) an overall score of how certain is the respons
Hi Axel,

parentalControl or contentLock are capabilities offered in some MNOs to lock content for specific lines.
These parameters give indication that, even if the owner of the contract is an adult (it will always be), the line may not be in use by him, but by other family members. So directly related with age verification API.
These parameters have been already validated by markets with age verification commercial interest and have been introduced as optional so, in case an MNO or country can not expose them, it is not mandatory.

Let us know if you have any other question.

Regards,
Clara

2025-01-14 07:13 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +    - `verifiedStatus`: true if the information provided was checked against another form of official identification, otherwise false.
@fernandopradocabrillo update to your suggested text

2025-01-14 07:18 UTC, AxelNennker commented on code/API_definitions/kyc-age-verification.yaml
> +        As it is possible that the person holding the contract and the person using the line may not be the same, the endpoint also admits a list of optional properties to be included in the request
@HuubAppelboom Then I guess I am looking for text that replaces "to improve the identification".

2025-01-14 07:47 UTC, HuubAppelboom commented on code/API_definitions/kyc-age-verification.yaml
> +        As it is possible that the person holding the contract and the person using the line may not be the same, the endpoint also admits a list of optional properties to be included in the request
@AxelNennker 

Here is a a suggestion:  replace "to improve the identification" with "to verifiy whether the End-User is the same person as the Subscriber"  
or alternatively replave it with  "to verify whether the person using the line is the same person as the one holding the contract"

2025-01-16 08:11 UTC, ToshiWakayama-KDDI approved these changes
LGTM.  Thanks very much.

2025-01-16 08:39 UTC, GillesInnov35 approved these changes

2025-01-16 08:45 UTC, GillesInnov35 commented
hi all, for includeContentLock or includeParentalControl I've made a proposition. I think that 'not_available' may be be returned in case of the MNO do not implement functionality. WDYT 
Thanks
Gilles

2025-01-16 09:04 UTC, ToshiWakayama-KDDI commented on code/API_definitions/kyc-age-verification.yaml
> +                  email: "federicaSanchez.Arjona@gmail.com"
Thanks @GillesInnov35 ,

But, from our side, as I commented before, we would like `contentLock` and `parentalControl` to be purely optional fundamentally (because of the very late proposal), meaning that API Providers/Operators do not have to implement any logic related to these two parameters and that `includeContentLock` and/or `includeParentalControl` can be ignored if a API Provider/Operator has not been implemented.  So, the current definition is fine.

If 'not_available' should be returned, API Providers/Operators have to implement required logic to understand the two attributes and to return 'not_available'.  It may be better to descript somewhere that if `includeContentLock` and/or `includeParentalControl` is put into the request and `ContentLock` and/or `ParentalControl` is not returned, it means the API Provider/Operator does not have the related function.  But, anyway, from our side, the current definition is fine, and your understanding would be appreciated.

Many thanks,
Toshi

2025-01-16 09:18 UTC, merged

2025-01-16 09:45 UTC, GillesInnov35 commented on code/API_definitions/kyc-age-verification.yaml
> +                  email: "federicaSanchez.Arjona@gmail.com"
Hi @ToshiWakayama-KDDI , thanks, I understand your comment. 
What I mean is as far as the 2 attributes are part of the design, the API Provider should manage the attribute's response even if the functionality has not been developed. If the consumer input them in the request body best practices may require a response. 

Gilles