Update README.md
camaraproject/KnowYourCustomer pull request #74
Opened 2024-04-12 04:39 UTC by wrathwolf

Add "Latest Release" Sticker
Removed unnecessary scope tag (Location)

Added URL for the new community meeting
I cleaned up the formatting of the contributing section for Confluence "GitHub Include" on the wiki.

2024-04-12 06:28 UTC, MarkusKuemmerle requested changes
I would keep the content of the previous "Contributorship and mailing list" section. It explains how to subscribe and unsubscribe to the mailing list, and how to send emails to the group.

Please make sure that as soon as this PR is merged also the content of the website subpage is updated

2024-04-12 09:34 UTC, ToshiWakayama-KDDI commented
Thanks, @wrathwolf , @MarkusKuemmerle,  

First of all, we have decieded to use the existing Teams Link for our next meeting on 16th of April, so, it would be appreciated if this PR could be merged after that.  
 
Secondly, 
> I would keep the content of the previous "Contributorship and mailing list" section. It explains how to subscribe and unsubscribe to the mailing list, and how to send emails to the group.

I would agree with this.  I think it would be better to keep the content of the previous "Contributorship and mailing list" section.

Thanks.

2024-04-12 16:29 UTC, hdamker requested changes
Please comment in https://github.com/camaraproject/Template_Lead_Repository/pull/3 regarding the upcoming structure for the README.md. That should be agreed before we touch/change all repositories.

2024-04-15 07:51 UTC, GillesInnov35 approved these changes

2024-05-07 09:51 UTC, fernandopradocabrillo approved these changes
LGTM in advance with a small correction

2024-05-07 09:51 UTC, fernandopradocabrillo commented on README.md
> +  * [Registration / Join](https://zoom-lfx.platform.linuxfoundation.org/meeting/95365880067?password=644c46e3-480b-426d-be9d-64ab4613aeb3)
Is this the correct link for the meeting? The one I have in the invitation is different

```suggestion
  * [Registration / Join](https://zoom-lfx.platform.linuxfoundation.org/meeting/96235150735?password=7e3fea67-a76e-4941-8a70-392cf5545917)
```

2024-05-09 16:46 UTC, hdamker commented on README.md
> +  * [Registration / Join](https://zoom-lfx.platform.linuxfoundation.org/meeting/95365880067?password=644c46e3-480b-426d-be9d-64ab4613aeb3)
@wrathwolf Can you check if the suggest link is correct and commit @fernandopradocabrillo suggestion if yes.

(both links belong to KYC, but 95365880067 seems to on the wrong time)

2024-05-09 16:49 UTC, hdamker commented
Within my commits I have aligned the Contribution part with the agreed template and added the meeting minutes link. In addition I have added the "Release Information" section. I will approve the changes now, but leave it to the Sub Project to finalise and merge.
@MarkusKuemmerle your comment is addressed, please confirm.

2024-05-09 16:49 UTC, hdamker submitted a review, later dismissed

2024-05-14 12:11 UTC, MarkusKuemmerle approved these changes
Please check that meeting link is correct

2024-05-14 12:22 UTC, fernandopradocabrillo commented
Hi @MarkusKuemmerle @wrathwolf 
We've held the meeting today in the link that I provided so I can confirm that it is the correct one

2024-05-14 12:25 UTC, fernandopradocabrillo commented
@hdamker I have also updated the confluence page with the meeting link

thanks

2024-05-14 12:25 UTC, fernandopradocabrillo approved these changes
LGTM

2024-05-14 12:27 UTC, hdamker commented
> @hdamker I have also updated the confluence page with the meeting link

@fernandopradocabrillo I have committed your suggested meeting link. Can you please approve again?

2024-05-22 08:52 UTC, ToshiWakayama-KDDI commented
LGTM.  

...Sorry that I have not been able to check this PR since April 12th. 

BR
Toshi
KDDI

2024-05-22 08:55 UTC, ToshiWakayama-KDDI approved these changes

2024-05-23 04:32 UTC, hdamker approved these changes

2024-06-01 01:11 UTC, ToshiWakayama-KDDI commented
Merging this long outstanding PR.  Should there be anything wrong, please let us know.  Thanks.

2024-06-01 01:12 UTC, merged